// <auto-generated />
using System;
using CustomerRegisterationFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerRegisterationFlow.Presistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241201172010_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerRegisterationFlow.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("HasAcceptedTerms")
                        .HasColumnType("bit");

                    b.Property<int>("ICNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBiometricLoginEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 1, 19, 20, 9, 827, DateTimeKind.Local).AddTicks(7772),
                            Email = "email1@email.com",
                            ICNumber = 123456,
                            LastModifiedBy = "System",
                            LastModifiedDate = new DateTime(2024, 12, 1, 19, 20, 9, 830, DateTimeKind.Local).AddTicks(2103),
                            Name = "Ahmed 1",
                            PasswordHash = "",
                            Phone = "0101010101",
                            Salt = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 1, 19, 20, 9, 830, DateTimeKind.Local).AddTicks(2993),
                            Email = "email2@email.com",
                            ICNumber = 1234567,
                            LastModifiedBy = "System",
                            LastModifiedDate = new DateTime(2024, 12, 1, 19, 20, 9, 830, DateTimeKind.Local).AddTicks(3000),
                            Name = "Ahmed 2",
                            PasswordHash = "",
                            Phone = "01010101012",
                            Salt = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 1, 19, 20, 9, 830, DateTimeKind.Local).AddTicks(3004),
                            Email = "email3@email.com",
                            ICNumber = 12345678,
                            LastModifiedBy = "System",
                            LastModifiedDate = new DateTime(2024, 12, 1, 19, 20, 9, 830, DateTimeKind.Local).AddTicks(3006),
                            Name = "Ahmed 3",
                            PasswordHash = "",
                            Phone = "01010101013",
                            Salt = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
